# Generated by Django 2.2.5 on 2019-09-09 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20190909_0812'),
    ]

    operations = [
        migrations.RunSQL("alter table app1_person add column age int;")
    ]
