# Generated by Django 2.2.5 on 2019-09-15 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_person_intn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='intc',
        ),
    ]
