# Generated by Django 2.2.5 on 2019-09-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_person_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='inta',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='intb',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
