# Generated by Django 2.2.5 on 2019-09-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20190912_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='intb',
            new_name='intc',
        ),
        migrations.RemoveField(
            model_name='person',
            name='inta',
        ),
        migrations.AddField(
            model_name='person',
            name='intd',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
